name: Jikpoze
author: Vincent Chalnot
description: A StageXL 2D game engine
dependencies:
  browser: any
  stagexl: any
  socket_io_client:
    git: https://github.com/rikulo/socket.io-client-dart.git
  socket_io:
    git: https://github.com/rikulo/socket.io-dart.git
transformers:
  - $dart2js:
      commandLineOptions: [--enable-experimental-mirrors]
