name: Jikpoze
author: Vincent Chalnot
description: A StageXL 2D game engine
dependencies:
  browser: any
  stagexl: any
  socket_io_client:
    git: https://github.com/rikulo/socket.io-client-dart.git
