name: jikpoze
author: Vincent Chalnot <vincent@sidus.fr>
description: A StageXL 2D game engine
homepage: https://github.com/BlueBearGaming/Jikpoze
version: '1.0.0'
dependencies:
  browser: ">=0.10.0+3 <0.11.0"
  stagexl: ">=1.3.1+3 <2.0.0"
  socket_io_client:
    git: https://github.com/rikulo/socket.io-client-dart.git
  socket_io:
    git: https://github.com/rikulo/socket.io-dart.git
transformers:
  - $dart2js:
      commandLineOptions: [--enable-experimental-mirrors]
